export enum OrderStatus {
    CREATED = 'CREATED',
    PICKING = 'PICKING',
    INVOICED = 'INVOICED',
    SHIPPED = 'SHIPPED',
    CANCELLED = 'CANCELLED',
    DELIVERED = 'DELIVERED',
    UNDELIVERED = 'UNDELIVERED',
    RETURNED = 'RETURNED',
    REPACK = 'REPACK',
    UNSUPPLIED = 'UNSUPPLIED',
    UNKNOWN = 'UNKNOWN',
}
